/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 19 03:15:28 GMT 2024
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.ParseError;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseError_ESTest extends ParseError_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseError parseError0 = new ParseError((-1842), "p/=");
      String string0 = parseError0.toString();
      assertEquals("-1842: p/=", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object[] objectArray0 = new Object[7];
      ParseError parseError0 = new ParseError(0, "9\"7L", objectArray0);
      assertEquals(0, parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseError parseError0 = new ParseError((-1842), "p/=");
      parseError0.getErrorMessage();
      assertEquals((-1842), parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseError parseError0 = new ParseError((-1842), "p/=");
      int int0 = parseError0.getPosition();
      assertEquals((-1842), int0);
  }
}
