/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 19 02:54:17 GMT 2024
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.XmlDeclaration;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlDeclaration_ESTest extends XmlDeclaration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("J`", "multiple", false);
      String string0 = xmlDeclaration0.toString();
      assertEquals("<?J`?>", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("@Qf", false);
      String string0 = xmlDeclaration0.getWholeDeclaration();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("-;", "-;", true);
      Attributes attributes0 = xmlDeclaration0.attributes();
      Attribute attribute0 = new Attribute("JJOuR:Rv*", "<4g5_GEwO2W", attributes0);
      attributes0.put(attribute0);
      assertEquals("#declaration", xmlDeclaration0.nodeName());
      
      String string0 = xmlDeclaration0.toString();
      assertEquals("<!-; JJOuR:Rv*=\"<4g5_GEwO2W\"!>", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration(".4_hiH3.", true);
      String string0 = xmlDeclaration0.name();
      assertEquals(".4_hiH3.", string0);
      assertEquals("#declaration", xmlDeclaration0.nodeName());
  }
}
